name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js v.23
      uses: actions/setup-node@v4
      with:
        node-version: 23
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Replace the backend endpoint
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js
    - name: Start Frontend
      run: npm run start &
    - name: Start Backend
      run: npm run server &
    - name: Install browser
      run: npx playwright install
    - name: Run tests
      run: npm run test

  deploy-be:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.LIBRARY_BACKEND_KEY }}
        api_key: ${{ secrets.LIBRARY_API_KEY }}
        wait_deploy: true

  deploy-fe:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.LIBRARY_FRONTEND_KEY }}
        api_key: ${{ secrets.LIBRARY_API_KEY }}
        wait_deploy: true